rm_category2name_v1:

  0: B_G
  1: B_1
  2: B_2
  3: B_3
  4: B_4
  5: B_5
  6: B_O
  7: B_Bs
  8: B_Bb

  9: R_G
  10: R_1
  11: R_2
  12: R_3
  13: R_4
  14: R_5
  15: R_O
  16: R_Bs
  17: R_Bb

  18: N_G
  19: N_1
  20: N_2
  21: N_3
  22: N_4
  23: N_5
  24: N_O
  25: N_Bs
  26: N_Bb

  27: P_G
  28: P_1
  29: P_2
  30: P_3
  31: P_4
  32: P_5
  33: P_O
  34: P_Bs
  35: P_Bb
